🚀 Update to goflow v0.53.0
rapidpro/mailroom pull request #185
Opened 2019-10-16 21:26 UTC by rowanseymour

2019-10-16 21:27 UTC, rowanseymour commented on hooks/classifier_called.go
> +		session.AddPreCommitEvent(insertHTTPLogsHook, log)
is it better do this... or change the event type to a list of logs? Assuming it doesn't make much difference in this case

2019-10-16 21:29 UTC, rowanseymour commented on models/http_logs.go
> +	h.h.RequestTime = elapsedMS
the event has time in millis.. so feels weird to convert to a duration just to create this.. then convert back to millis

2019-10-17 18:49 UTC, nicpottier requested changes

2019-10-17 18:49 UTC, nicpottier commented on hooks/classifier_called.go
> +		session.AddPreCommitEvent(insertHTTPLogsHook, log)
They all get wrapped up into a list in the end anyways, so probably clearest to do single items.

2019-10-17 18:49 UTC, nicpottier commented on models/http_logs.go
> +	h.h.RequestTime = elapsedMS
This I disagree with. Durations should be passed as durations in go interfaces. Can understand if we have  JSON objects that want to convert to MS, but interfaces should be typed.

2019-10-17 19:12 UTC, rowanseymour commented on models/http_logs.go
> +	h.h.RequestTime = elapsedMS
The problem is that the value isn't a golang duration (count of nanoseconds).. it's duration as a count of milliseconds. It's seems weird to convert milliseconds to nano-seconds and back to milliseconds just so you can have a type in this function call.. and obscures the fact we're throwing away accuracy. 

I'll change it back if you really want but if it's the typing your after then I think we just have something like `type Millis int`

2019-10-17 19:15 UTC, nicpottier commented on models/http_logs.go
> +	h.h.RequestTime = elapsedMS
Its a duration, the resolution of that duration (based on how it was measured or in this case how it was saved to an event) doesn't really apply. The interface to create a log should take a duration, regardless of the resolution of that duration. That it gets converted to milliseconds when written to the DB is an implementation detail that should be hidden through the interface.

This one I really do feel strongly about, so yes, please change to `time.Duration`

2019-10-17 19:26 UTC, rowanseymour commented on models/http_logs.go
> +	h.h.RequestTime = elapsedMS
Changed

2019-10-17 19:47 UTC, nicpottier commented on models/http_logs.go
> +	h.h.RequestTime = elapsedMS
Gracias.

2019-10-17 19:47 UTC, merged