RocketChat Ticketer
rapidpro/mailroom pull request #333
Opened 2020-08-14 20:06 UTC by koallann

https://github.com/nyaruka/rapidpro/pull/2909

2020-10-19 18:54 UTC, rowanseymour commented on services/tickets/rocketchat/testdata/event_callback.json
> +    "body": "{\"type\":\"agent-message\",\"ticketID\":\"88bfa1dc-be33-45c2-b469-294ecb0eba90\",\"visitor\":{\"token\":\"1234\"},\"data\":{\"text\":\"We can help\"}}",
don't need to encode as string here - should work as JSON

2020-10-19 18:55 UTC, rowanseymour commented
@koallann this looks good but you still want to add attachment support right? We're planning code freeze for RapidPro in 2 weeks time so would be great to get this included.

2020-10-20 13:39 UTC, koallann commented
@rowanseymour almost fully implemented, we only need an [adjustment](https://github.com/rapidpro/rapidpro/issues/1309#issuecomment-709223973) to incoming attachments.

2020-10-20 14:17 UTC, rowanseymour commented
@koallann ok maybe just hold off on the incoming attachments thing because I started looking at what that would require for mailgun/email ticketers and that's not going to work with fetching URLs because the attachments are embedded in the request... I'm going to add stuff today to support getting attachments from different places.

But this is ready minus incoming attachments?

2020-10-20 14:39 UTC, rowanseymour commented on services/tickets/rocketchat/web_test.go
> +	db.MustExec(`INSERT INTO tickets_ticket(id, uuid, org_id, contact_id, ticketer_id, status, subject, body, opened_on, modified_on)
there's now a `testdata.InsertOpenTicket` util function

2020-10-20 18:10 UTC, koallann commented
Yes @rowanseymour

2020-10-21 14:09 UTC, rowanseymour commented
@koallann ok have just merged #374 which reworks incoming attachments but RocketChat should be basically the same as Zendesk with the addition of passing some headers

2020-10-22 13:01 UTC, koallann commented
done @rowanseymour

2020-10-22 15:32 UTC, rowanseymour requested changes

2020-10-22 15:32 UTC, rowanseymour commented on services/tickets/rocketchat/service.go
> +	// to fully support the RocketChat ticketer, look up extra fields from ticket body for now
I appreciate this is maybe how you guys are using RocketChat right now but I think we need a way of sharing fields etc with external ticketing services which provides a more uniform experience across different ticketing services, i.e. body isn't expected to be JSON for other services, and this approach would mean the ticket list view page becomes a list of big JSON blobs.

It's also not a great approach in that you're sending a snaphot of field values when the ticket is opened but users in RocketChat won't see changes to those field values.

For Zendesk we haven't yet implemented syncing field values but it will probably either be

 1. The Zendesk app can fetch them from the RapidPro API
 2. Every time we push a message to Zendesk we push a set of field values that can be configured on the ticketer in RApidPro

2020-10-22 15:32 UTC, rowanseymour commented on services/tickets/rocketchat/service.go
> +	return errors.New("RocketChat ticket type doesn't support reopening")
Need some way of telling the RapidPro UI to not try re-opening tickets associated with RocketChat ticketers

2020-10-22 15:32 UTC, rowanseymour commented on services/tickets/rocketchat/service.go
> +	// to fully support the RocketChat ticketer, look up extra fields from ticket body for now
I think maybe we remove this for now, and revisit how to send field values later.

2020-10-22 16:52 UTC, koallann commented on services/tickets/rocketchat/service.go
> +	// to fully support the RocketChat ticketer, look up extra fields from ticket body for now
I totally agree with you, but these fields are essential for our customers because each of them has a different context of use. The data in these fields is very important for agents in RocketChat to be able to make the information triage. With this information, the agent can decide to get the conversation or forward it to another department more appropriate to the user/contact, for example.

2020-10-22 19:04 UTC, rowanseymour commented on services/tickets/rocketchat/service.go
> +	// to fully support the RocketChat ticketer, look up extra fields from ticket body for now
Are you already running this as a fork, or is this to replace existing changes you've made to RP to support RocketChat? This feels like a "hack" so we could merge without it and then you can put it back into your fork..

2020-10-22 19:32 UTC, koallann commented on services/tickets/rocketchat/service.go
> +	// to fully support the RocketChat ticketer, look up extra fields from ticket body for now
We're still not running this code, but we can run that hack on a fork, so I'll remove it.

2020-10-23 16:16 UTC, rowanseymour commented on services/tickets/rocketchat/client_test.go
> +	baseURL = "https://my.rocket.chat/api/apps/public/684202ed-1461-4983-9ea7-fde74b15026c"
@koallann where can we see the source for this?

2020-10-23 16:39 UTC, koallann commented on services/tickets/rocketchat/client_test.go
> +	baseURL = "https://my.rocket.chat/api/apps/public/684202ed-1461-4983-9ea7-fde74b15026c"
The UUID in this url is the RocketChat app ID and the app API is [here](https://github.com/Ilhasoft/Rocket.Chat.App-Tickets/tree/release/v1.0.0#api-reference).

2020-11-03 20:19 UTC, koallann commented
Hey @rowanseymour, any more changes here?

2020-11-03 20:57 UTC, rowanseymour commented
@koallann I don't think so tho we're focused on getting the Rocket.Chat channel PRs live and tested first

2020-11-05 15:01 UTC, merged