🔁 Add task to resend messages
rapidpro/mailroom pull request #420
Opened 2021-04-23 20:15 UTC by rowanseymour

Part of #177 which would let us remove last of the topup and message sending code in RP

2021-04-26 17:48 UTC, rowanseymour commented on core/models/msgs.go
> -func MarkMessagesPending(ctx context.Context, db Queryer, msgs []*Msg) error {
not sure it's worth having a separate function for each status

2021-04-27 15:16 UTC, nicpottier requested changes
Why are we cloning the message? This feels like some remnant of the previous implementation that just adds complication. I'd rather we just re-queue it and make sure any kind of double sending cache or whatnot is cleared so that works. Cloning just seems odd especially given how often this occurs.

2021-04-27 15:26 UTC, rowanseymour commented
Good question I was just copying what we had in RapidPro.. maybe we did it this way to ensure it uses another topup? Will rework this to just requeue.

2021-04-27 16:29 UTC, nicpottier commented
Was thinking about this on the dog walk and I think it may have to do with the relayer, though that sounds like something perhaps worth revisiting.

2021-05-04 21:42 UTC, rowanseymour commented
@nicpottier in order for mailroom to clear the double-send protection, it would have to know the specifics of courier's date-based redis sets we use for that... maybe mailroom queues it to courier with a `is_resend` flag set and that skips double send checking in courier?

2021-05-05 14:33 UTC, nicpottier commented
Ya, that makes sense, can look at that today.

2021-05-06 19:04 UTC, rowanseymour commented
@nicpottier reworked to reset message state rather than clone messages

2021-05-06 19:05 UTC, rowanseymour commented on core/models/msgs.go
> +		msg.m.SentOn = dates.ZeroDateTime
not sure about this.. I think it'll put a zero time in the json queued to courier.. but that doesn't matter?

2021-05-06 20:25 UTC, nicpottier approved these changes

2021-05-06 20:25 UTC, nicpottier commented on core/models/msgs.go
> +		msg.m.SentOn = dates.ZeroDateTime
Does `omit_empty` leave it out if it is a zero value? Feels risky / weird having a 0 value there.

2021-05-06 20:50 UTC, rowanseymour commented on core/models/msgs.go
> +		msg.m.SentOn = dates.ZeroDateTime
Apparently not but aren't we always queuing `sent_on="0001-01-01T00:00:00Z"` to courier? I need to verify but I can't see how the regular queuing code would be any different.

2021-05-06 20:58 UTC, rowanseymour commented on core/models/msgs.go
> +		msg.m.SentOn = dates.ZeroDateTime
Ok now I've checked and we always queue to courier with `sent_on="0001-01-01T00:00:00Z"` and `next_attempt="0001-01-01T00:00:00Z"` because those are non-null in mailroom's model

2021-05-06 21:12 UTC, merged

2021-05-10 16:12 UTC, nicpottier commented
Ya, if that's what we were doing then fine. Maybe this is an argument to add `null.Time` to our null package at some point, feels risky / slopping to be writing real dates.

2021-05-10 17:16 UTC, nicpottier commented
Just realized when looking at this further that both `queued_on` and `sent_on` are actually non-null in our DB too, which seems like the first thing to tweak / fix!