Write failed messages when missing channel or URNs
rapidpro/mailroom pull request #551
Opened 2021-12-13 15:46 UTC by norkans7

2021-12-13 15:54 UTC, rowanseymour requested changes

2021-12-13 15:54 UTC, rowanseymour commented on core/handlers/msg_created.go
> +			urn, _ := models.GetOrCreateURN(ctx, tx, oa, scene.ContactID(), event.Msg.URN())
we still want to err if this fails.. I think you want a check for `event.Msg.URN() != urns.NilURN` above

2021-12-13 15:54 UTC, rowanseymour commented on core/handlers/msg_created.go
>  		channel = oa.ChannelByUUID(event.Msg.Channel().UUID)
likewise.. it's still an error for the engine to pass back an invalid channel

2021-12-13 15:54 UTC, rowanseymour commented on core/models/msgs.go
> +	MsgFailedURN        = MsgFailedReason("U")
We can merge these since the engine looks for compatible pairs of channel+URN and either returns a message with both set or neither set.. maybe `MsgFailedDestination` ? That's what the engine calls a channel+URN pair

2021-12-13 15:54 UTC, rowanseymour commented on core/models/msgs.go
> +		msg.SetURN(urns.NilURN)
again I think this should be `if msg.URN then SetURN`

2021-12-13 17:49 UTC, norkans7 commented on core/handlers/msg_created.go
>  		channel = oa.ChannelByUUID(event.Msg.Channel().UUID)
when channel is `nil` the event will be ignored and not handled here?
I thought we need to ignore that error here so the message is saved with the Failed status

2021-12-14 14:42 UTC, merged

2021-12-14 14:42 UTC, rowanseymour approved these changes