WIP interrupt channel
rapidpro/mailroom pull request #670
Opened 2022-10-04 21:16 UTC by norkans7

2022-10-06 18:31 UTC, rowanseymour requested changes

2022-10-06 18:31 UTC, rowanseymour commented on core/models/msgs.go
> +func FailMessages(ctx context.Context, db Queryer, rp *redis.Pool, oa *OrgAssets, msgs []*Msg) ([]*Msg, error) {
Why do we need to load the messages? I think you can just directly update messages with status = Q,P,E for a given channel. We can still do it batches like...

```
WITH rows AS (
  SELECT id FROM msgs_msg WHERE ... LIMIT 1000
)
DELETE FROM msgs_msg
WHERE id IN (SELECT id FROM rows)
```

And just keep calling that until it deletes zero rows

2022-10-06 18:31 UTC, rowanseymour commented on core/msgio/courier.go
> +redis.call("ZREMRANGEBYSCORE", queueKey .. "/0", "-inf", "inf")
can't this just `DEL` the entire set?

2022-10-06 20:08 UTC, norkans7 commented on core/models/msgs.go
> +func FailMessages(ctx context.Context, db Queryer, rp *redis.Pool, oa *OrgAssets, msgs []*Msg) ([]*Msg, error) {
Updated

2022-10-10 20:20 UTC, rowanseymour commented on core/tasks/channels/interrupt_channel.go
> +	channels, err := models.GetChannelsByID(ctx, db, channelIDs)
after we switch over RP to use this task rather than `interrupt_sessions`, we can replace this with `models.GetChannelByID(ctx, db, channelID)`

2022-10-10 20:21 UTC, rowanseymour requested changes

2022-10-10 20:21 UTC, rowanseymour commented on core/tasks/channels/interrupt_channel.go
> +		return err
use `errors.Wrap` and add context

2022-10-10 20:23 UTC, rowanseymour commented
@norkans7 just wrap some of those errors and I think this is looking good

2022-10-11 16:06 UTC, rowanseymour approved these changes

2022-10-11 16:07 UTC, merged